### ISSUE TITLE
Add a panel launch type

### ISSUE THREAD

**Issue by claudiodangelis** [claudiodangelis/popup-for-keep#20]

**Comment by GitTom** [comment]
I don't know whether this is a normal/easy thing to implement, but would be great if the panel could have a "keep on top" toggle.

**Comment by claudiodangelis** [comment]
Hi, you mean keeping the popup open all the time? Unfortunately that is not possilble as per technical limitation of the Chrome Extension platform. 

However, you can use this button to detach the popup from the toolbar and have a little floating window with Keep:

![image](https://cloud.githubusercontent.com/assets/941963/25986740/6ff1a506-36f1-11e7-8e37-1a2fd9514b98.png)

**Comment by GitTom** [comment]
I mean to keep the floating window "on top of" chrome, eg. so you can use it for some notes while you move between tabs, without having it dissapear behind chrome each time you change tabs or otherwise touch chrome.
