### ISSUE TITLE
Popup-UI label selection

### ISSUE THREAD

**Issue by MartinLichtblau** [claudiodangelis/popup-for-keep#21]
The "Add label" function shows the label-selection-box under other UI-elements and renders the whole function unfunctional.

![image](https://cloud.githubusercontent.com/assets/4956334/14275429/84517c18-fb17-11e5-9db1-18a6af577d84.png)

**Comment by claudiodangelis** [comment]
Nice find, thanks for reporting.

**Comment by claudiodangelis** [comment]
First of all: sorry for the **HUGE** delay. I tried to reproduce the issue, but apparently Google already fixed that by itself.

I will close this issue for now.
