### ISSUE TITLE
Add currently browsing page to Keep

### ISSUE THREAD

**Issue by willhughes** [claudiodangelis/popup-for-keep#25]
It'd be great if it could add the current page title + URL to Keep with a single click. 

The official extension does this, but it requires signing into Chrome as the same user you want to use Keep with - so doesn't work for me in the office.

**Comment by claudiodangelis** [comment]
Hi,

If I understand correctly what you need, you can already do that, just do a
right click somewhere in the middle of the page then choose "Add to Keep".
After clicking, a new Keep page will open and a new note will be created
with title and url.

For reference, the above applies to selections too: highlight some text in
the page, then right click, then "Add selection to Keep".

Hope this answer your question!

Claudio d'Angelis

claudiodangelis@gmail.com
Il 29/apr/2016 06:26, "Will Hughes" <notifications@github.com> ha scritto:

**Comment by willhughes** [comment]
Ah, my bad - yes, it does do that. Didn't see that. 

Thanks!

**Comment by claudiodangelis** [comment]
For sake of completeness, Google released an official Keep extension last week that does the "add to page" job better than mine. Maybe you want to take a look at it: https://chrome.google.com/webstore/detail/google-keep-chrome-extens
