### ISSUE TITLE
Getting this at work, on home PC all ok. https://keep.google.com/keep opens fine too at work

### ISSUE THREAD

**Issue by mk89pwnz** [claudiodangelis/popup-for-keep#32]
http://i.imgur.com/ybla4Yv.jpg

**Comment by claudiodangelis** [comment]
Hi, thanks for reaching out, it's the first time I see this error. I will
research this in a few days,

Claudio

>

**Comment by mk89pwnz** [comment]
Thanks, maybe it have smth to do with my language options? All google keep is Lithuanian. Basically I have to clear chrome data to make it work :(

**Comment by claudiodangelis** [comment]
Hi, sorry for the late follow up, the link you posted expired, and honestly I can't remember what was the issue you've been running into. Any clue? Thanks
