### ISSUE TITLE
Pop-out button gone?

### ISSUE THREAD

**Issue by JVimes** [claudiodangelis/popup-for-keep#46]
The pop-out button disappeared from the main UI. Just making sure that was on purpose. I liked it for discoverability (pop-out still available via icon right click menu, less discoverable).

![image](https://user-images.githubusercontent.com/6148201/36632740-adc051dc-1947-11e8-8139-2f43df5cb4a2.png)

**Comment by claudiodangelis** [comment]
Hi John, the button is gone, if you right-click on the menubar icon you can
choose "Open Google Keep in a floating popup" and that would pop Keep out.

Please let me know if it works as expected, as it's a feature I was not
able to test myself.

Thank you!

Claudio d'Angelis

claudiodangelis@gmail.com
Skype: claudiodangelis
Phone: (+39) 329 2933194



2018-02-24 17:48 GMT+01:00 John <notifications@github.com>:

**Comment by JVimes** [comment]
Aw, okay. Thanks for letting me know! Right click command works.
